import {
  Institution,
  ServicePackage,
  AuthCode,
  KnowledgePointNode,
  QuestionItem,
  TeacherItem,
  StudentItem,
  ParentGuardianship,
  AuditLogItem,
  PlatformStats,
} from './types';

export const initialPlatformStats: PlatformStats = {
  activeInstitutions: 138,
  activeInstitutionsGrowth: 4,
  platformRemainingQuota: '1.2M',
  totalCoveredStudents: 45210,
  alertInstitutionsCount: 5,
  totalPackageActivationRate: 94.2,
  dailyAiRequests: 128500,
};

export const initialInstitutions: Institution[] = [
  {
    id: 'INS-2023001',
    name: '浙江大学附属中学',
    code: 'INS-ZJDFZ',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '李明',
    phone: '138-8888-0001',
    email: 'liming@zju-hs.edu.cn',
    adminAccount: 'admin_zjdfz',
    adminPassword: '123456',
    totalQuota: 100000,
    remainingQuota: 75402,
    teacherCount: 124,
    studentCount: 2150,
    status: 'active',
    createdAt: '2023-09-01',
    updatedAt: '2026-07-28',
  },
  {
    id: 'INS-2022091',
    name: '博雅语言学院',
    code: 'INS-BYYY',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '陈静',
    phone: '150-1111-2222',
    email: 'chenjing@boya.edu.cn',
    adminAccount: 'admin_boya',
    adminPassword: '123456',
    totalQuota: 20000,
    remainingQuota: 0,
    isFrozen: true,
    teacherCount: 0,
    studentCount: 0,
    status: 'inactive',
    createdAt: '2022-09-15',
    updatedAt: '2026-05-10',
  },
  {
    id: 'INS-2023045',
    name: '上海青葱教育培训中心',
    code: 'INS-SHQC',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '张伟',
    phone: '139-0000-1234',
    email: 'zhangwei@qingcong.com',
    adminAccount: 'admin_qingcong',
    adminPassword: '123456',
    totalQuota: 50000,
    remainingQuota: 6012, // 12% 额度告急
    teacherCount: 45,
    studentCount: 890,
    status: 'active',
    createdAt: '2023-11-20',
    updatedAt: '2026-07-29',
  },
  {
    id: 'INS-2024012',
    name: '北京十一学校',
    code: 'INS-BJ11',
    region: 'huabei',
    regionName: '华北地区',
    contactPerson: '王晓华',
    phone: '136-2222-3333',
    email: 'wangxh@bjsy.edu.cn',
    adminAccount: 'admin_bjsy',
    adminPassword: '123456',
    totalQuota: 150000,
    remainingQuota: 112000,
    teacherCount: 180,
    studentCount: 3400,
    status: 'active',
    createdAt: '2024-01-10',
    updatedAt: '2026-07-25',
  },
  {
    id: 'INS-2024088',
    name: '深圳实验学校',
    code: 'INS-SZSY',
    region: 'huanan',
    regionName: '华南地区',
    contactPerson: '林嘉豪',
    phone: '137-9999-8888',
    email: 'linjh@szsy.edu.cn',
    adminAccount: 'admin_szsy',
    adminPassword: '123456',
    totalQuota: 120000,
    remainingQuota: 98500,
    teacherCount: 140,
    studentCount: 2800,
    status: 'active',
    createdAt: '2024-03-18',
    updatedAt: '2026-07-26',
  },
  {
    id: 'INS-2023102',
    name: '华中师范大学第一附属中学',
    code: 'INS-HZSY',
    region: 'central',
    regionName: '华中地区',
    contactPerson: '赵云',
    phone: '135-7777-6666',
    email: 'zhaoyun@hzsy.edu.cn',
    adminAccount: 'admin_hzsy',
    adminPassword: '123456',
    totalQuota: 80000,
    remainingQuota: 3200, // 4% 告急
    teacherCount: 95,
    studentCount: 1950,
    status: 'active',
    createdAt: '2023-10-12',
    updatedAt: '2026-07-27',
  },
];

export const initialServicePackages: ServicePackage[] = [
  {
    id: 'PKG-001',
    code: 'SP-SINGLE-LOW',
    name: '单科低量包',
    type: 'single_low',
    typeName: '单科低量',
    quotaCost: 50,
    dailyAiLimit: 15,
    durationDays: 365,
    description: '激活领用时允许任选 1 个内容包（如【初中数学包】），低频日常答题与基础 AI 概念辅导。',
    status: 'active',
    subjectRequirement: 'single',
    contentPackageMode: 'single',
    includedContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包', '初中英语词汇与阅读包'],
  },
  {
    id: 'PKG-002',
    code: 'SP-SINGLE-HIGH',
    name: '单科高量包',
    type: 'single_high',
    typeName: '单科高量',
    quotaCost: 120,
    dailyAiLimit: 50,
    durationDays: 365,
    description: '激活领用时任选 1 个深度内容包，支持每日高频 AI 导师对话与深度错题剖析。',
    status: 'active',
    subjectRequirement: 'single',
    contentPackageMode: 'single',
    includedContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版高中数学必修与选修包', '人教版高中物理竞赛包'],
  },
  {
    id: 'PKG-003',
    code: 'SP-ALL-LOW',
    name: '全科低量包',
    type: 'all_low',
    typeName: '全科低量',
    quotaCost: 180,
    dailyAiLimit: 30,
    durationDays: 365,
    description: '包含所选学段的多个主要内容包（语/数/英/物/化/生内容包），日常多科低频陪伴。',
    status: 'active',
    subjectRequirement: 'all',
    contentPackageMode: 'multiple',
    includedContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包', '人教版初中生物精选内容包', '初中英语词汇与阅读包'],
  },
  {
    id: 'PKG-004',
    code: 'SP-ALL-HIGH',
    name: '全科高量包',
    type: 'all_high',
    typeName: '全科高量',
    quotaCost: 350,
    dailyAiLimit: 100,
    durationDays: 365,
    description: '全科无缝 AI 陪伴，包含全部初高中精选内容包，支持多内容包无限制解答与智能诊断。',
    status: 'active',
    subjectRequirement: 'all',
    contentPackageMode: 'multiple',
    includedContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包', '人教版高中数学必修与选修包', '人教版高中物理竞赛包', '初中全科中考提分通关内容包'],
  },
];

export const initialAuthCodes: AuthCode[] = [
  {
    id: 'AC-1001',
    code: 'KQ-8829-9102-1823',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    studentId: 'STU-001',
    studentName: '王小明',
    packageId: 'PKG-004',
    packageName: '全科高量包',
    packageType: 'all_high',
    quotaConsumed: 350,
    createdAt: '2026-07-20 10:30',
    expireAt: '2026-08-19 10:30',
    activatedAt: '2026-07-21 14:20',
    status: 'used',
  },
  {
    id: 'AC-1002',
    code: 'KQ-9931-1045-8821',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    studentId: 'STU-002',
    studentName: '李思思',
    packageId: 'PKG-002',
    packageName: '单科高量包',
    packageType: 'single_high',
    quotaConsumed: 120,
    createdAt: '2026-07-25 15:00',
    expireAt: '2026-08-24 15:00',
    status: 'pending',
  },
  {
    id: 'AC-1003',
    code: 'KQ-1102-3341-9980',
    institutionId: 'INS-2023045',
    institutionName: '上海青葱教育培训中心',
    teacherId: 'TCH-002',
    teacherName: '周强老师',
    studentId: 'STU-003',
    studentName: '陈立',
    packageId: 'PKG-001',
    packageName: '单科低量包',
    packageType: 'single_low',
    quotaConsumed: 50,
    createdAt: '2026-06-01 09:15',
    expireAt: '2026-07-01 09:15',
    status: 'expired',
  },
  {
    id: 'AC-1004',
    code: 'KQ-7712-4410-3329',
    institutionId: 'INS-2022091',
    institutionName: '博雅语言学院',
    teacherId: 'TCH-003',
    teacherName: '高林老师',
    packageId: 'PKG-003',
    packageName: '全科低量包',
    packageType: 'all_low',
    quotaConsumed: 180,
    createdAt: '2026-05-01 11:00',
    expireAt: '2026-05-31 11:00',
    status: 'revoked',
  },
];

export const initialKnowledgePoints: KnowledgePointNode[] = [
  // 级别 1
  {
    id: 'KP-L1-01',
    code: 'KP-MATH-CH1',
    name: '一元一次方程',
    level: 1,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    questionCount: 42,
    status: 'active',
  },
  // 级别 2
  {
    id: 'KP-L2-01',
    code: 'KP-MATH-CH1-S1',
    name: '解方程基本步骤与性质',
    level: 2,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L1-01',
    questionCount: 28,
    status: 'active',
  },
  // 级别 3 (最小考点)
  {
    id: 'KP-L3-01',
    code: 'KP-MATH-CH1-S1-P1',
    name: '移项与合并同类项规则',
    level: 3,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L2-01',
    questionCount: 18,
    status: 'active',
  },
  {
    id: 'KP-L3-02',
    code: 'KP-MATH-CH1-S1-P2',
    name: '去括号与去分母应用',
    level: 3,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L2-01',
    questionCount: 10,
    status: 'active',
  },
  // 级别 1 (物理)
  {
    id: 'KP-L1-02',
    code: 'KP-PHYS-CH2',
    name: '牛顿运动定律',
    level: 1,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    questionCount: 35,
    status: 'active',
  },
  {
    id: 'KP-L2-02',
    code: 'KP-PHYS-CH2-S2',
    name: '牛顿第二定律综合应用',
    level: 2,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    parentId: 'KP-L1-02',
    questionCount: 20,
    status: 'active',
  },
  {
    id: 'KP-L3-03',
    code: 'KP-PHYS-CH2-S2-P1',
    name: '超重与失重状态加速度判别',
    level: 3,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    parentId: 'KP-L2-02',
    questionCount: 0, // 提示无可练题
    status: 'active',
  },
];

export const initialQuestions: QuestionItem[] = [
  {
    id: 'Q-2026001',
    title: '一元一次方程去括号计算题',
    content: '解方程：2(x - 3) - 3(x + 1) = 5。求 x 的值。',
    options: ['A. x = -14', 'B. x = 14', 'C. x = -4', 'D. x = 4'],
    answer: 'A. x = -14',
    analysis: '展开括号：2x - 6 - 3x - 3 = 5。合并同类项：-x - 9 = 5。移项：-x = 14，故 x = -14。',
    subject: '数学',
    stage: '初中',
    grade: '初一',
    textbook: '人教版',
    difficulty: '基础',
    type: '选择题',
    knowledgePointLevel1Id: 'KP-L1-01',
    knowledgePointLevel2Id: 'KP-L2-01',
    knowledgePointLevel3Id: 'KP-L3-01',
    knowledgePointPathName: '数学 > 一元一次方程 > 移项与合并同类项规则',
    status: 'active',
    createdAt: '2026-07-10 14:00',
  },
  {
    id: 'Q-2026002',
    title: '含分母一元一次方程压轴应用',
    content: '解方程：(2x + 1)/3 - (5x - 1)/6 = 1。',
    answer: 'x = 1',
    analysis: '两边同乘以 6 得：2(2x + 1) - (5x - 1) = 6。4x + 2 - 5x + 1 = 6，-x + 3 = 6，x = -3。',
    subject: '数学',
    stage: '初中',
    grade: '初一',
    textbook: '人教版',
    difficulty: '提升',
    type: '解答题',
    knowledgePointLevel1Id: 'KP-L1-01',
    knowledgePointLevel2Id: 'KP-L2-01',
    knowledgePointLevel3Id: 'KP-L3-02',
    knowledgePointPathName: '数学 > 一元一次方程 > 去括号与去分母应用',
    status: 'active',
    createdAt: '2026-07-15 11:20',
  },
];

export const initialTeachers: TeacherItem[] = [
  {
    id: 'TCH-001',
    name: '张敏老师',
    account: 'zhangmin_zj',
    phone: '138-1111-2222',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    studentCount: 45,
    allocatedQuota: 10000,
    remainingQuota: 6200,
    permissions: {
      canEditContent: true,
      canImportStudents: true,
      canManageClass: true,
      canRedeemPackage: true,
      canViewReport: true,
    },
    status: 'active',
    createdAt: '2025-09-01',
  },
  {
    id: 'TCH-002',
    name: '周强老师',
    account: 'zhouqiang_qc',
    phone: '139-2222-3333',
    institutionId: 'INS-2023045',
    institutionName: '上海青葱教育培训中心',
    studentCount: 30,
    allocatedQuota: 5000,
    remainingQuota: 800,
    permissions: {
      canEditContent: true,
      canImportStudents: true,
      canManageClass: true,
      canRedeemPackage: true,
      canViewReport: true,
    },
    status: 'active',
    createdAt: '2026-02-15',
  },
];

export const initialStudents: StudentItem[] = [
  {
    id: 'STU-001',
    name: '王小明',
    nickname: '小明同学',
    account: 'wangxm2026',
    grade: '初一',
    school: '浙江大学附属中学',
    textbook: '人教版',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    subjects: ['数学', '物理'],
    serviceStatus: 'active',
    serviceExpireAt: '2027-07-21',
    totalStudyHours: 42.5,
    totalQuestions: 380,
    accuracyRate: 85,
    errorCount: 57,
    unreviewedErrorCount: 8,
  },
  {
    id: 'STU-002',
    name: '李思思',
    nickname: '思思加油',
    account: 'lisisi2026',
    grade: '高一',
    school: '浙江大学附属中学',
    textbook: '人教版',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    subjects: ['数学', '物理', '化学'],
    serviceStatus: 'none',
    totalStudyHours: 12.0,
    totalQuestions: 95,
    accuracyRate: 72,
    errorCount: 26,
    unreviewedErrorCount: 12,
  },
];

export const initialParentGuardianships: ParentGuardianship[] = [
  {
    id: 'G-101',
    parentName: '王建国 (王小明父亲)',
    parentPhone: '138-9999-0000',
    studentId: 'STU-001',
    studentName: '王小明',
    institutionName: '浙江大学附属中学',
    relationType: '父亲',
    status: 'active',
    createdAt: '2026-07-21 16:00',
  },
  {
    id: 'G-102',
    parentName: '李强 (李思思父亲)',
    parentPhone: '139-8888-1111',
    studentId: 'STU-002',
    studentName: '李思思',
    institutionName: '浙江大学附属中学',
    relationType: '父亲',
    status: 'pending',
    createdAt: '2026-07-28 09:30',
  },
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: 'LOG-8001',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '机构管理',
    action: '调增机构采购总额度',
    target: '浙江大学附属中学 (INS-2023001)',
    details: '分配新增采购额度 +20,000 点，机构总额度由 80,000 变为 100,000 点。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-28 18:22:10',
  },
  {
    id: 'LOG-8002',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '服务包管理',
    action: '修改服务包配置',
    target: '全科高量包 (PKG-004)',
    details: '修改每日 AI 额度限制为 100 次/天，消耗额度为 350 点。已激活存量不追溯受影响。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-27 11:05:44',
  },
  {
    id: 'LOG-8003',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '额度授权码',
    action: '作废未激活授权码',
    target: '博雅语言学院 (AC-1004)',
    details: '作废码：KQ-7712-4410-3329 (已过期未激活)。阻止后续微信身份绑定。',
    ipAddress: '10.240.0.15',
    timestamp: '2026-07-26 09:40:12',
  },
  {
    id: 'LOG-8004',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '题库管理',
    action: '批量导入精选题库',
    target: '人教版初一数学题库.xlsx',
    details: '成功解析 150 道题目，新增 142 道，更新 8 道，关联三级知识点成功率 100%。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-25 16:15:30',
  },
];
