import {
  Institution,
  ServicePackage,
  AuthCode,
  KnowledgePointNode,
  QuestionItem,
  TeacherItem,
  StudentItem,
  ParentGuardianship,
  AuditLogItem,
  PlatformStats,
  OrderLedgerRecord,
  ContentPackageItem,
  CooperationPlan,
} from './types';

export const initialContentPackages: ContentPackageItem[] = [
  { id: 'CP-01', code: 'CP-MATH-CZ', name: '人教版初中数学全套内容包', subjectId: 'SUB-01', subject: '初中数学', stage: '初中', kpCount: 156, questionCount: 1280, status: 'active', description: '引用初中数学下已发布的知识点与题目' },
  { id: 'CP-02', code: 'CP-PHYS-CZ', name: '人教版初中物理精选内容包', subjectId: 'SUB-02', subject: '初中物理', stage: '初中', kpCount: 98, questionCount: 840, status: 'active', description: '引用初中物理下已发布的知识点与题目' },
  { id: 'CP-03', code: 'CP-CHEM-CZ', name: '人教版初中化学核心内容包', subjectId: 'SUB-03', subject: '初中化学', stage: '初中', kpCount: 75, questionCount: 620, status: 'active', description: '引用初中化学下已发布的知识点与题目' },
  { id: 'CP-04', code: 'CP-MATH-GZ', name: '人教版高中数学必修与选择性必修包', subjectId: 'SUB-06', subject: '高中数学', stage: '高中', kpCount: 210, questionCount: 1850, status: 'active', description: '引用高中数学下已发布的知识点与题目' },
  { id: 'CP-05', code: 'CP-ENG-CZ', name: '初中英语词汇与阅读专项包', subjectId: 'SUB-04', subject: '初中英语', stage: '初中', kpCount: 110, questionCount: 950, status: 'active', description: '引用初中英语下已发布的知识点与题目' },
];

export const initialCooperationPlans: CooperationPlan[] = [
  { id: 'PLAN-001', code: 'PLAN-CZ-SCIENCE', name: '初中理科标准方案', contentPackageIds: ['CP-01', 'CP-02', 'CP-03'], servicePackageIds: ['PKG-001', 'PKG-002'], suggestedInitialQuota: 50000, cooperationDurationDays: 365, status: 'active', version: 1, institutionCount: 2, createdAt: '2026-07-01', updatedAt: '2026-08-01' },
  { id: 'PLAN-002', code: 'PLAN-GZ-FULL', name: '高中全科旗舰方案', contentPackageIds: ['CP-04'], servicePackageIds: ['PKG-003', 'PKG-004'], suggestedInitialQuota: 100000, cooperationDurationDays: 365, status: 'active', version: 2, institutionCount: 1, createdAt: '2026-07-10', updatedAt: '2026-08-05' },
];

export const initialPlatformStats: PlatformStats = {
  activeInstitutions: 138,
  activeInstitutionsGrowth: 4,
  platformRemainingQuota: '1.2M',
  totalCoveredStudents: 45210,
  alertInstitutionsCount: 5,
  totalPackageActivationRate: 94.2,
  dailyAiRequests: 128500,
};

export const initialInstitutions: Institution[] = [
  {
    id: 'INS-2023001',
    name: '浙江大学附属中学',
    code: 'INS-ZJDFZ',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '李明',
    phone: '138-8888-0001',
    email: 'liming@zju-hs.edu.cn',
    adminAccount: 'admin_zjdfz',
    adminPassword: '123456',
    totalQuota: 100000,
    remainingQuota: 75402,
    availableContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包', '初中英语词汇与阅读包'],
    availableServicePackageIds: ['PKG-001', 'PKG-002', 'PKG-003', 'PKG-004'],
    teacherCount: 124,
    studentCount: 2150,
    status: 'active',
    contractAmount: 680000,
    contractStatus: 'active',
    contractExpireAt: '2027-08-31',
    createdAt: '2023-09-01',
    updatedAt: '2026-07-28',
  },
  {
    id: 'INS-2022091',
    name: '博雅语言学院',
    code: 'INS-BYYY',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '陈静',
    phone: '150-1111-2222',
    email: 'chenjing@boya.edu.cn',
    adminAccount: 'admin_boya',
    adminPassword: '123456',
    totalQuota: 20000,
    remainingQuota: 0,
    availableContentPackages: ['初中英语词汇与阅读包'],
    availableServicePackageIds: ['PKG-001'],
    isFrozen: true,
    teacherCount: 0,
    studentCount: 0,
    status: 'inactive',
    contractAmount: 120000,
    contractStatus: 'expired',
    contractExpireAt: '2026-05-31',
    createdAt: '2022-09-15',
    updatedAt: '2026-05-10',
  },
  {
    id: 'INS-2023045',
    name: '上海青葱教育培训中心',
    code: 'INS-SHQC',
    region: 'huadong',
    regionName: '华东地区',
    contactPerson: '张伟',
    phone: '139-0000-1234',
    email: 'zhangwei@qingcong.com',
    adminAccount: 'admin_qingcong',
    adminPassword: '123456',
    totalQuota: 50000,
    remainingQuota: 6012, // 12% 额度告急
    availableContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包'],
    availableServicePackageIds: ['PKG-001', 'PKG-002', 'PKG-003'],
    teacherCount: 45,
    studentCount: 890,
    status: 'active',
    contractAmount: 360000,
    contractStatus: 'expiring',
    contractExpireAt: '2026-09-30',
    createdAt: '2023-11-20',
    updatedAt: '2026-07-29',
  },
  {
    id: 'INS-2024012',
    name: '北京十一学校',
    code: 'INS-BJ11',
    region: 'huabei',
    regionName: '华北地区',
    contactPerson: '王晓华',
    phone: '136-2222-3333',
    email: 'wangxh@bjsy.edu.cn',
    adminAccount: 'admin_bjsy',
    adminPassword: '123456',
    totalQuota: 150000,
    remainingQuota: 112000,
    availableContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版高中数学必修与选修包', '人教版高中物理竞赛包'],
    availableServicePackageIds: ['PKG-001', 'PKG-002', 'PKG-004'],
    teacherCount: 180,
    studentCount: 3400,
    status: 'active',
    contractAmount: 920000,
    contractStatus: 'active',
    contractExpireAt: '2027-01-31',
    createdAt: '2024-01-10',
    updatedAt: '2026-07-25',
  },
  {
    id: 'INS-2024088',
    name: '深圳实验学校',
    code: 'INS-SZSY',
    region: 'huanan',
    regionName: '华南地区',
    contactPerson: '林嘉豪',
    phone: '137-9999-8888',
    email: 'linjh@szsy.edu.cn',
    adminAccount: 'admin_szsy',
    adminPassword: '123456',
    totalQuota: 120000,
    remainingQuota: 98500,
    availableContentPackages: ['人教版初中数学全套内容包', '人教版初中物理精选内容包', '人教版初中化学核心内容包', '人教版初中生物精选内容包', '初中英语词汇与阅读包'],
    availableServicePackageIds: ['PKG-001', 'PKG-003'],
    teacherCount: 140,
    studentCount: 2800,
    status: 'active',
    contractAmount: 760000,
    contractStatus: 'active',
    contractExpireAt: '2027-03-31',
    createdAt: '2024-03-18',
    updatedAt: '2026-07-26',
  },
  {
    id: 'INS-2023102',
    name: '华中师范大学第一附属中学',
    code: 'INS-HZSY',
    region: 'central',
    regionName: '华中地区',
    contactPerson: '赵云',
    phone: '135-7777-6666',
    email: 'zhaoyun@hzsy.edu.cn',
    adminAccount: 'admin_hzsy',
    adminPassword: '123456',
    totalQuota: 80000,
    remainingQuota: 3200, // 4% 告急
    availableContentPackages: ['人教版初中数学全套内容包', '人教版高中数学必修与选修包'],
    availableServicePackageIds: ['PKG-002'],
    teacherCount: 95,
    studentCount: 1950,
    status: 'active',
    contractAmount: 510000,
    contractStatus: 'expiring',
    contractExpireAt: '2026-10-15',
    createdAt: '2023-10-12',
    updatedAt: '2026-07-27',
  },
];

export const initialServicePackages: ServicePackage[] = [
  {
    id: 'PKG-001',
    code: 'SP-SINGLE-LOW',
    name: '单科低量包',
    type: 'single_low',
    typeName: '单科低量',
    quotaCost: 50,
    includedAiUsage: 200000,
    durationDays: 365,
    description: '适合单科学生的低频日常答题与基础 AI 概念辅导。',
    status: 'active',
    subjectRequirement: 'single',
  },
  {
    id: 'PKG-002',
    code: 'SP-SINGLE-HIGH',
    name: '单科高量包',
    type: 'single_high',
    typeName: '单科高量',
    quotaCost: 120,
    includedAiUsage: 1000000,
    durationDays: 365,
    description: '适合单科高频使用，支持 AI 导师对话与深度错题剖析。',
    status: 'active',
    subjectRequirement: 'single',
  },
  {
    id: 'PKG-003',
    code: 'SP-ALL-LOW',
    name: '全科低量包',
    type: 'all_low',
    typeName: '全科低量',
    quotaCost: 180,
    includedAiUsage: 2000000,
    durationDays: 365,
    description: '适合多学科日常低频使用，提供基础 AI 学习陪伴。',
    status: 'active',
    subjectRequirement: 'all',
  },
  {
    id: 'PKG-004',
    code: 'SP-ALL-HIGH',
    name: '全科高量包',
    type: 'all_high',
    typeName: '全科高量',
    quotaCost: 350,
    includedAiUsage: 5000000,
    durationDays: 365,
    description: '适合多学科高频使用，支持 AI 解答与智能诊断。',
    status: 'active',
    subjectRequirement: 'all',
  },
];

export const initialAuthCodes: AuthCode[] = [
  {
    id: 'AC-1001',
    code: 'KQ-8829-9102-1823',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    studentId: 'STU-001',
    studentName: '王小明',
    packageId: 'PKG-004',
    packageName: '全科高量包',
    packageType: 'all_high',
    quotaConsumed: 350,
    createdAt: '2026-07-20 10:30',
    expireAt: '2026-08-19 10:30',
    activatedAt: '2026-07-21 14:20',
    status: 'used',
  },
  {
    id: 'AC-1002',
    code: 'KQ-9931-1045-8821',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    studentId: 'STU-002',
    studentName: '李思思',
    packageId: 'PKG-002',
    packageName: '单科高量包',
    packageType: 'single_high',
    quotaConsumed: 120,
    createdAt: '2026-07-25 15:00',
    expireAt: '2026-08-24 15:00',
    status: 'pending',
  },
  {
    id: 'AC-1003',
    code: 'KQ-1102-3341-9980',
    institutionId: 'INS-2023045',
    institutionName: '上海青葱教育培训中心',
    teacherId: 'TCH-002',
    teacherName: '周强老师',
    studentId: 'STU-003',
    studentName: '陈立',
    packageId: 'PKG-001',
    packageName: '单科低量包',
    packageType: 'single_low',
    quotaConsumed: 50,
    createdAt: '2026-06-01 09:15',
    expireAt: '2026-07-01 09:15',
    status: 'expired',
  },
  {
    id: 'AC-1004',
    code: 'KQ-7712-4410-3329',
    institutionId: 'INS-2022091',
    institutionName: '博雅语言学院',
    teacherId: 'TCH-003',
    teacherName: '高林老师',
    packageId: 'PKG-003',
    packageName: '全科低量包',
    packageType: 'all_low',
    quotaConsumed: 180,
    createdAt: '2026-05-01 11:00',
    expireAt: '2026-05-31 11:00',
    status: 'revoked',
  },
];

export const initialOrderLedger: OrderLedgerRecord[] = [
  {
    id: 'ORD-1001',
    orderNo: 'ORD-20260728-001',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    type: 'credit_inflow',
    typeName: '机构合同额度到账',
    paymentAmount: 680000,
    creditChange: 100000,
    status: 'completed',
    operatorName: '财务管理员',
    timestamp: '2026-07-28 10:20',
    reason: '年度服务合同首款',
  },
  {
    id: 'ORD-1002',
    orderNo: 'ORD-20260729-014',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    type: 'package_redeem',
    typeName: '授权码服务包兑换',
    paymentAmount: 0,
    creditChange: -350,
    status: 'completed',
    operatorName: '王教师',
    timestamp: '2026-07-29 09:15',
    reason: '兑换全科高量包',
  },
  {
    id: 'ORD-1003',
    orderNo: 'ORD-20260730-021',
    institutionId: 'INS-2023045',
    institutionName: '上海青葱教育培训中心',
    type: 'ai_usage_pack_buy',
    typeName: '购买',
    paymentAmount: 2999,
    creditChange: 50000,
    status: 'completed',
    operatorName: '机构管理员',
    timestamp: '2026-07-30 14:36',
    reason: '额度预警后续费',
  },
  {
    id: 'ORD-1004',
    orderNo: 'ORD-20260731-008',
    institutionId: 'INS-2022091',
    institutionName: '博雅语言学院',
    type: 'refund',
    typeName: '服务退款',
    paymentAmount: -12000,
    creditChange: -20000,
    status: 'refunded',
    operatorName: '财务管理员',
    timestamp: '2026-07-31 17:05',
    reason: '机构停用后终止履约',
  },
];

export const initialKnowledgePoints: KnowledgePointNode[] = [
  // 级别 1
  {
    id: 'KP-L1-01',
    code: 'KP-MATH-CH1',
    name: '一元一次方程',
    level: 1,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    questionCount: 42,
    status: 'active',
  },
  // 级别 2
  {
    id: 'KP-L2-01',
    code: 'KP-MATH-CH1-S1',
    name: '解方程基本步骤与性质',
    level: 2,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L1-01',
    questionCount: 28,
    status: 'active',
  },
  // 级别 3 (最小考点)
  {
    id: 'KP-L3-01',
    code: 'KP-MATH-CH1-S1-P1',
    name: '移项与合并同类项规则',
    level: 3,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L2-01',
    questionCount: 18,
    status: 'active',
    coreContent: '理解移项与合并同类项的依据，掌握一元一次方程的标准求解步骤。',
    learningObjective: '能够独立完成移项、合并同类项并检验方程解。',
    teachingSuggestion: '用等式两边同时进行相同运算的直观模型，配合易错题进行对比练习。',
  },
  {
    id: 'KP-L3-02',
    code: 'KP-MATH-CH1-S1-P2',
    name: '去括号与去分母应用',
    level: 3,
    subject: '数学',
    grade: '初一',
    textbook: '人教版',
    parentId: 'KP-L2-01',
    questionCount: 10,
    status: 'active',
    coreContent: '掌握去括号、去分母的运算法则及其在方程中的应用。',
    learningObjective: '能够规范地运用去括号与去分母解决一元一次方程。',
    teachingSuggestion: '先训练符号变化，再通过分步书写和回代检验巩固运算准确性。',
  },
  // 级别 1 (物理)
  {
    id: 'KP-L1-02',
    code: 'KP-PHYS-CH2',
    name: '牛顿运动定律',
    level: 1,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    questionCount: 35,
    status: 'active',
  },
  {
    id: 'KP-L2-02',
    code: 'KP-PHYS-CH2-S2',
    name: '牛顿第二定律综合应用',
    level: 2,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    parentId: 'KP-L1-02',
    questionCount: 20,
    status: 'active',
  },
  {
    id: 'KP-L3-03',
    code: 'KP-PHYS-CH2-S2-P1',
    name: '超重与失重状态加速度判别',
    level: 3,
    subject: '物理',
    grade: '高一',
    textbook: '人教版',
    parentId: 'KP-L2-02',
    questionCount: 0, // 提示无可练题
    status: 'active',
    coreContent: '理解超重、失重现象与加速度方向之间的关系。',
    learningObjective: '能够根据运动状态判断物体的超重或失重状态。',
    teachingSuggestion: '结合电梯、过山车等生活情境，引导学生先判断加速度方向再分析支持力。',
  },
];

export const initialQuestions: QuestionItem[] = [
  {
    id: 'Q-2026001',
    title: '一元一次方程去括号计算题',
    content: '解方程：2(x - 3) - 3(x + 1) = 5。求 x 的值。',
    options: ['A. x = -14', 'B. x = 14', 'C. x = -4', 'D. x = 4'],
    answer: 'A. x = -14',
    analysis: '展开括号：2x - 6 - 3x - 3 = 5。合并同类项：-x - 9 = 5。移项：-x = 14，故 x = -14。',
    subject: '数学',
    stage: '初中',
    grade: '初一',
    textbook: '人教版',
    difficulty: '基础',
    type: '选择题',
    knowledgePointLevel1Id: 'KP-L1-01',
    knowledgePointLevel2Id: 'KP-L2-01',
    knowledgePointLevel3Id: 'KP-L3-01',
    knowledgePointPathName: '数学 > 一元一次方程 > 移项与合并同类项规则',
    status: 'active',
    createdAt: '2026-07-10 14:00',
  },
  {
    id: 'Q-2026002',
    title: '含分母一元一次方程压轴应用',
    content: '解方程：(2x + 1)/3 - (5x - 1)/6 = 1。',
    answer: 'x = 1',
    analysis: '两边同乘以 6 得：2(2x + 1) - (5x - 1) = 6。4x + 2 - 5x + 1 = 6，-x + 3 = 6，x = -3。',
    subject: '数学',
    stage: '初中',
    grade: '初一',
    textbook: '人教版',
    difficulty: '提升',
    type: '解答题',
    knowledgePointLevel1Id: 'KP-L1-01',
    knowledgePointLevel2Id: 'KP-L2-01',
    knowledgePointLevel3Id: 'KP-L3-02',
    knowledgePointPathName: '数学 > 一元一次方程 > 去括号与去分母应用',
    status: 'active',
    createdAt: '2026-07-15 11:20',
  },
];

export const initialTeachers: TeacherItem[] = [
  {
    id: 'TCH-001',
    name: '张敏老师',
    subject: '数学',
    account: 'zhangmin_zj',
    loginPassword: 'Teacher@2026!',
    phone: '138-1111-2222',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    studentCount: 45,
    allocatedQuota: 10000,
    remainingQuota: 6200,
    permissions: {
      canEditContent: true,
      canImportStudents: true,
      canManageClass: true,
      canRedeemPackage: true,
      canViewReport: true,
    },
    status: 'active',
    createdAt: '2025-09-01',
  },
  {
    id: 'TCH-002',
    name: '周强老师',
    subject: '数学',
    account: 'zhouqiang_qc',
    loginPassword: 'Teacher@2026!',
    phone: '139-2222-3333',
    institutionId: 'INS-2023045',
    institutionName: '上海青葱教育培训中心',
    studentCount: 30,
    allocatedQuota: 5000,
    remainingQuota: 800,
    permissions: {
      canEditContent: true,
      canImportStudents: true,
      canManageClass: true,
      canRedeemPackage: true,
      canViewReport: true,
    },
    status: 'active',
    createdAt: '2026-02-15',
  },
  {
    id: 'TCH-004', name: '陈雨老师', subject: '物理', account: 'chenyu_zj', loginPassword: 'Teacher@2026!', phone: '136-5555-1201',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', studentCount: 2,
    allocatedQuota: 0, remainingQuota: 0,
    permissions: { canEditContent: true, canImportStudents: true, canManageClass: true, canRedeemPackage: false, canViewReport: true },
    status: 'active', createdAt: '2026-04-08',
  },
  {
    id: 'TCH-005', name: '刘洋老师', subject: '生物', account: 'liuyang_zj', loginPassword: 'Teacher@2026!', phone: '135-6666-1202',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', studentCount: 1,
    allocatedQuota: 0, remainingQuota: 0,
    permissions: { canEditContent: true, canImportStudents: true, canManageClass: true, canRedeemPackage: false, canViewReport: true },
    status: 'active', createdAt: '2026-05-16',
  },
  {
    id: 'TCH-003', name: '高林老师', subject: '英语', account: 'gaolin_tch', loginPassword: 'Teacher@2026!', phone: '137-3333-4444',
    institutionId: 'INS-3007001', institutionName: '博雅语言学院', studentCount: 18,
    allocatedQuota: 1000, remainingQuota: 320,
    permissions: { canEditContent: false, canImportStudents: true, canManageClass: true, canRedeemPackage: true, canViewReport: true },
    status: 'inactive', createdAt: '2026-03-10',
  },
];

export const initialStudents: StudentItem[] = [
  {
    id: 'STU-001',
    name: '王小明',
    nickname: '小明同学',
    account: 'wangxm2026',
    phone: '13812345678',
    loginPassword: 'Student@2026!',
    grade: '初一',
    className: '初一（1）班',
    school: '浙江大学附属中学',
    textbook: '人教版',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    teacherAssignments: [{ teacherId: 'TCH-004', teacherName: '陈雨老师', subject: '物理' }],
    subjects: ['数学', '物理'],
    subjectLearning: [
      { subject: '数学', studyHours: 25.5, totalQuestions: 230, accuracyRate: 88, errorCount: 28, unreviewedErrorCount: 3 },
      { subject: '物理', studyHours: 17, totalQuestions: 150, accuracyRate: 80, errorCount: 29, unreviewedErrorCount: 5 },
    ],
    serviceStatus: 'active',
    serviceExpireAt: '2027-07-21',
    totalStudyHours: 42.5,
    totalQuestions: 380,
    accuracyRate: 85,
    errorCount: 57,
    unreviewedErrorCount: 8,
  },
  {
    id: 'STU-002',
    name: '李思思',
    nickname: '思思加油',
    account: 'lisisi2026',
    phone: '13987654321',
    loginPassword: 'Student@2026!',
    grade: '高一',
    className: '高一（2）班',
    school: '浙江大学附属中学',
    textbook: '人教版',
    institutionId: 'INS-2023001',
    institutionName: '浙江大学附属中学',
    teacherId: 'TCH-001',
    teacherName: '张敏老师',
    teacherAssignments: [
      { teacherId: 'TCH-004', teacherName: '陈雨老师', subject: '物理' },
      { teacherId: 'TCH-005', teacherName: '刘洋老师', subject: '生物' },
    ],
    subjects: ['数学', '物理', '化学', '生物'],
    subjectLearning: [
      { subject: '数学', studyHours: 4, totalQuestions: 30, accuracyRate: 77, errorCount: 7, unreviewedErrorCount: 3 },
      { subject: '物理', studyHours: 3, totalQuestions: 25, accuracyRate: 68, errorCount: 8, unreviewedErrorCount: 4 },
      { subject: '化学', studyHours: 2.5, totalQuestions: 20, accuracyRate: 75, errorCount: 5, unreviewedErrorCount: 2 },
      { subject: '生物', studyHours: 2.5, totalQuestions: 20, accuracyRate: 65, errorCount: 6, unreviewedErrorCount: 3 },
    ],
    serviceStatus: 'none',
    totalStudyHours: 12.0,
    totalQuestions: 95,
    accuracyRate: 72,
    errorCount: 26,
    unreviewedErrorCount: 12,
  },
  {
    id: 'STU-003', name: '赵子涵', nickname: '子涵', account: 'zhaozh2026', phone: '13710001003', loginPassword: 'Student@2026!',
    grade: '初二', className: '初二（1）班', school: '浙江大学附属中学', textbook: '人教版',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', teacherId: 'TCH-004', teacherName: '陈雨老师',
    subjects: ['数学', '物理'], serviceStatus: 'active', serviceExpireAt: '2027-06-30',
    totalStudyHours: 28.5, totalQuestions: 246, accuracyRate: 81, errorCount: 47, unreviewedErrorCount: 9,
  },
  {
    id: 'STU-004', name: '孙浩然', nickname: '浩然', account: 'sunhr2026', phone: '13710001004', loginPassword: 'Student@2026!',
    grade: '初二', className: '初二（2）班', school: '浙江大学附属中学', textbook: '人教版',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', teacherId: 'TCH-004', teacherName: '陈雨老师',
    subjects: ['数学', '物理'], serviceStatus: 'none',
    totalStudyHours: 6.5, totalQuestions: 58, accuracyRate: 69, errorCount: 18, unreviewedErrorCount: 11,
  },
  {
    id: 'STU-005', name: '周可欣', nickname: '可欣', account: 'zhouke2026', phone: '13710001005', loginPassword: 'Student@2026!',
    grade: '高一', className: '高一（1）班', school: '浙江大学附属中学', textbook: '人教版',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', teacherId: 'TCH-005', teacherName: '刘洋老师',
    subjects: ['数学', '物理', '化学'], serviceStatus: 'none',
    totalStudyHours: 18, totalQuestions: 132, accuracyRate: 76, errorCount: 32, unreviewedErrorCount: 7,
  },
  {
    id: 'STU-006', name: '吴一诺', nickname: '一诺', account: 'wuyinuo2026', phone: '13710001006', loginPassword: 'Student@2026!',
    grade: '初一', className: '', school: '浙江大学附属中学', textbook: '人教版',
    institutionId: 'INS-2023001', institutionName: '浙江大学附属中学', teacherId: '', teacherName: '',
    subjects: ['数学'], serviceStatus: 'none',
    totalStudyHours: 0, totalQuestions: 0, accuracyRate: 0, errorCount: 0, unreviewedErrorCount: 0,
  },
];

export const initialParentGuardianships: ParentGuardianship[] = [
  {
    id: 'G-101',
    parentName: '王建国 (王小明父亲)',
    parentPhone: '138-9999-0000',
    studentId: 'STU-001',
    studentName: '王小明',
    institutionName: '浙江大学附属中学',
    relationType: '父亲',
    status: 'active',
    createdAt: '2026-07-21 16:00',
  },
  {
    id: 'G-102',
    parentName: '李强 (李思思父亲)',
    parentPhone: '139-8888-1111',
    studentId: 'STU-002',
    studentName: '李思思',
    institutionName: '浙江大学附属中学',
    relationType: '父亲',
    status: 'pending',
    createdAt: '2026-07-28 09:30',
  },
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: 'LOG-8001',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '机构管理',
    action: '调增机构采购总额度',
    target: '浙江大学附属中学 (INS-2023001)',
    details: '分配新增采购额度 +20,000 点，机构总额度由 80,000 变为 100,000 点。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-28 18:22:10',
  },
  {
    id: 'LOG-8002',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '服务包管理',
    action: '修改服务包配置',
    target: '全科高量包 (PKG-004)',
    details: '修改服务包包含 AI 用量为 500 万，消耗额度为 350 点。已激活存量不追溯受影响。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-27 11:05:44',
  },
  {
    id: 'LOG-8003',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '额度授权码',
    action: '作废未激活授权码',
    target: '博雅语言学院 (AC-1004)',
    details: '作废码：KQ-7712-4410-3329 (已过期未激活)。阻止后续微信身份绑定。',
    ipAddress: '10.240.0.15',
    timestamp: '2026-07-26 09:40:12',
  },
  {
    id: 'LOG-8004',
    operatorName: '超级管理员 (Super Admin)',
    operatorRole: 'Super Admin',
    module: '题库管理',
    action: '批量导入精选题库',
    target: '人教版初一数学题库.xlsx',
    details: '成功解析 150 道题目，新增 142 道，更新 8 道，关联三级知识点成功率 100%。',
    ipAddress: '10.240.0.12',
    timestamp: '2026-07-25 16:15:30',
  },
];
