import React from 'react';

export const controlClassName = 'w-full rounded-xl border border-[#D8E1EA] bg-white px-3 py-2.5 text-[13px] text-[#0F172A] outline-none transition-colors placeholder:text-[#94A3B8] focus:border-[#16B45B] focus:ring-2 focus:ring-[#16B45B]/10';

export const FieldLabel: React.FC<React.PropsWithChildren<{ label: string; required?: boolean; hint?: string }>> = ({ label, required, hint, children }) => <label className="block"><span className="mb-1.5 flex items-center justify-between gap-2 text-[12px] font-bold text-[#334155]"><span>{label}{required && <span className="ml-1 text-[#EF4444]">*</span>}</span>{hint && <span className="font-normal text-[#94A3B8]">{hint}</span>}</span>{children}</label>;

export const ChoiceCard: React.FC<{ checked: boolean; title: string; meta?: string; onChange: () => void }> = ({ checked, title, meta, onChange }) => <button type="button" role="checkbox" aria-checked={checked} onClick={onChange} className={`flex w-full items-start gap-3 rounded-xl border p-3 text-left transition-all ${checked ? 'border-[#16B45B] bg-[#F0FBF4] shadow-[0_0_0_1px_rgba(22,180,91,0.06)]' : 'border-[#E2E8F0] bg-white hover:border-[#A7E4BE] hover:bg-[#FBFDFC]'}`}><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border ${checked ? 'border-[#16B45B] bg-[#16B45B] text-white' : 'border-[#CBD5E1] bg-white'}`}>{checked && <span className="material-symbols-outlined text-[13px]">check</span>}</span><span className="min-w-0"><span className="block text-[12.5px] font-bold text-[#0F172A]">{title}</span>{meta && <span className="mt-0.5 block text-[11px] text-[#64748B]">{meta}</span>}</span></button>;

export const DialogShell: React.FC<React.PropsWithChildren<{ title: string; description?: string; onClose: () => void; footer: React.ReactNode; icon?: string }>> = ({ title, description, onClose, footer, icon = 'deployed_code', children }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0F172A]/45 p-4 backdrop-blur-[2px]"><section role="dialog" aria-modal="true" aria-labelledby="shared-dialog-title" className="flex max-h-[88vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-white/60 bg-white shadow-[0_24px_64px_rgba(15,23,42,0.22)]"><header className="flex items-start justify-between gap-4 border-b border-[#E2E8F0] px-6 py-5"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#E8F7EE] text-[#16B45B]"><span className="material-symbols-outlined text-[21px]">{icon}</span></div><div><h3 id="shared-dialog-title" className="text-[18px] font-bold text-[#0F172A]">{title}</h3>{description && <p className="mt-1 text-[12px] leading-5 text-[#64748B]">{description}</p>}</div></div><button type="button" aria-label="关闭" onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-lg text-[#64748B] hover:bg-[#F1F5F9] hover:text-[#0F172A]"><span className="material-symbols-outlined text-[20px]">close</span></button></header><div className="overflow-y-auto bg-[#F8FAFC]/70 px-6 py-5 custom-scrollbar">{children}</div><footer className="flex items-center justify-end gap-2 border-t border-[#E2E8F0] bg-white px-6 py-4">{footer}</footer></section></div>;
